project: 
  type: website

website:
  navbar:
    background: primary
    search: false
    logo: files/FINALfulllogoTA2023_wt.png
    left:
      - text: "Deutsch"
        file: index.qmd
      - text: "English"
        file: english.qmd





