project:
  type: book
  output-dir: docs

book:
  title: "Einführung in Generative AI"
  author: "Tilo Flasche & Jan Bischoff"
  date: "15.11.2023"
  # description: "A one-day workshop introducing you to the Python programming language for Data Science"
  chapters:
    - index.qmd

  #logo: files/logo.png
  # sidebar:
  #   tools:
  #     - icon: box-arrow-up-right
  #       href: https://lukas-juergensmeier.com/
github-repo: tech-academy-ev/efl-2023-generative-ai

#bibliography: references.bib

format:
  html:
    theme: cosmo



